name: unet
features: [16, 32]
fc_bottleneck: true
fc_recurrent: true  # only useful when fc_bottleneck is true
conv_recurrent: true  # use conv layers for recurrent connections
hidden_dim: 512     # only useful when fc_bottleneck is true
output_timesteps: 1
initial_scaling: 4  # initial scaling factor for input size, used to calculate downscaling factor
use_plif_encoder: true
use_plif_recurrent: true
use_plif_decoder: true
init_tau_recurrent: 20.0
init_tau_encoder: 2.0
init_tau_decoder: 2.0
