# configs/default.yaml
description: >
  sequence training using last membrane potential as out

data:
  # Common settings
  loader: "demo"           # "demo" or "det"
  batch_size: 4
  num_workers: 4          

    # → for demoloader only:
  num_samples: 1000
  time_steps: 10
  input_size: [32,32]
  moving: true
  noise: 0.1
  heavy_noise: 0.4
  heavy_noise_prob: 0.3

  # → for det loader only:
  downscale: 8            # integer down-sampling factor
  

model:
  encoder_channels: [4, 8]
  hidden_dim: 512  # if null, defaults to flattened encoder output
  name: det_unet
  recurrent: true
  output_timesteps: 1
  use_plif_encoder: false
  use_plif_recurrent: false
  use_plif_decoder: false
  init_tau: 2.0

train:
  epochs: 10
  lr: 0.0005
  amp: false
  device: auto
  save_intermediate: false

log:
  vis_interval: -1
