# configs/default.yaml
description: >
  sequence training without recurrent layer using only last timestep membrane potential as outout

data:
  # Common settings
  loader: "demo"           # "demo" or "det"
  batch_size: 4
  num_workers: 4          

  # → for demo loader only:
  num_samples: 100
  time_steps: 10
  input_size: [32,32]
  moving: true
  noise: 0.1
  heavy_noise: 0.4
  heavy_noise_prob: 0.3

  # → for det loader only:
  downscale: 2            # integer down-sampling factor
  

model:
  in_channels: 1
  out_channels: 1
  encoder_channels: [4, 8]
  hidden_dim: null  # if null, defaults to flattened encoder output
  name: det_recurrent_full_plif
  recurrent: true
  output_timesteps: 1
  use_plif_encoder: false
  use_plif_recurrent: false
  use_plif_decoder: false
  init_tau: 2.0

train:
  epochs: 10
  lr: 0.001
  amp: false
  device: cpu
  save_intermediate: false

log:
  vis_interval: 1