# configs/default.yaml

data:
  num_samples: 1000
  batch_size: 4
  time_steps: 10
  input_size: [32, 32]

model:
  in_channels: 1
  out_channels: 1
  encoder_channels: [4, 8]
  hidden_dim: null  # if null, defaults to flattened encoder output

train:
  epochs: 11
  lr: 0.001
  amp: false
  device: cpu

log:
  log_dir: runs/demo
  checkpoint_dir: checkpoints
  vis_interval: 5