description: >
  Recurrent UNet training configuration with 10 timesteps and high pos weight scaling

defaults:
  model: unet # base or unet
  data: det   # det or demo

train:
  epochs: 100
  lr: 0.001
  amp: false
  device: auto
  save_intermediate: false

log:
  vis_interval: 30
