description: >
  U-Net with initial scaling

defaults:
  model: lanesnn # base, unet or lanesnn
  data: det # det, carla or demo

train:
  epochs: 5
  lr: 0.001
  amp: false
  device: auto
  save_intermediate: false

log:
  vis_interval: 1
