description: >
  Spiking SNN training with config profiles

defaults:
  model: unet # base or unet
  data: det   # det or demo

train:
  epochs: 10
  lr: 0.0005
  amp: false
  device: auto
  save_intermediate: false

log:
  vis_interval: -1
