description: >
  Recurrent bigger UNet training to compare with static

defaults:
  model: unet # base or unet
  data: carla   # det, carla or demo

train:
  epochs: 5
  lr: 0.001
  amp: false
  device: auto
  save_intermediate: false

log:
  vis_interval: 5
