description: >
  Spiking SNN training smaller unet

defaults:
  model: unet # base or unet
  data: det   # det or demo

train:
  epochs: 50
  lr: 0.001
  amp: false
  device: auto
  save_intermediate: false

log:
  vis_interval: -1
