description: >
  Recurrent UNet training configuration

defaults:
  model: unet # base or unet
  data: demo   # det or demo

train:
  epochs: 10
  lr: 0.001
  amp: false
  device: auto
  save_intermediate: false

log:
  vis_interval: 1
